name: Gosec
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v5
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: --exclude-dir=examples --exclude-dir=aws ./...
